import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="container header-container">
            <div className="logo">
              <Link href="/">
                <img src="/images/logo.png" alt="Pure Botanica" />
              </Link>
            </div>
            <nav>
              <Link href="/product">Sản phẩm</Link>
              <Link href="/about">Về chúng tôi</Link>
              <Link href="/contact">Liên hệ</Link>
              <Link href="/news">Tin tức</Link>
            </nav>
            <div className="icons">
              <div className="icon">🔍</div>
              <Link href="/cart">
                <div className="icon">🛒</div>
              </Link>
              <Link href="/register">
                <div className="icon">👤</div>
              </Link>
            </div>
          </div>
        </header>

        <main>{children}</main>

        <footer className="footer">
          <div className="footer-container">
            <div className="footer-logo">
              <img src="/images/logo_web.png" alt="Pure Botanica Logo" />
              <p className="footer-slogan">
                "Nurtured by Nature <br /> Perfected for You"
              </p>
            </div>
            <div className="footer-links">
              <div className="footer-column">
                <h4>SẢN PHẨM</h4>
                <ul>
                  <li><Link href="#">Chăm sóc da</Link></li>
                  <li><Link href="#">Chăm sóc tóc</Link></li>
                  <li><Link href="#">Chăm sóc cơ thể</Link></li>
                  <li><Link href="#">Bộ trang điểm</Link></li>
                  <li><Link href="#">Hương thơm</Link></li>
                  <li><Link href="#">Mẹ và bé</Link></li>
                </ul>
              </div>
              <div className="footer-column">
                <h4>CHÍNH SÁCH</h4>
                <ul>
                  <li><Link href="#">Chính sách bảo mật</Link></li>
                  <li><Link href="#">Chính sách đổi trả</Link></li>
                  <li><Link href="#">Chính sách giao hàng</Link></li>
                  <li><Link href="#">Chính sách bảo mật thông tin</Link></li>
                </ul>
              </div>
            </div>
            <div className="footer-newsletter">
              <h4>Đăng ký email để nhận thông tin</h4>
              <p>Hãy là người đầu tiên biết về sự kiện mới, sản phẩm mới</p>
              <form>
                <input type="email" placeholder="Nhập email của bạn..." />
                <button type="submit">Đăng Ký</button>
              </form>
              <div className="footer-address">
                <p>
                  <i className="fa-solid fa-location-dot"></i> Tòa nhà QTSC9 (tòa T), đường Tô Ký, phường Tân Chánh Hiệp, Quận 12, TP Hồ Chí Minh
                </p>
              </div>
            </div>
          </div>
          <hr style={{ border: "none", height: "1px", backgroundColor: "rgba(0, 0, 0, 0.1)", marginTop: "50px", marginBottom: "0" }} />
          <div className="footer-bottom">
            <p>© 2025 LLC</p>
            <div className="footer-payment">
              <img src="/images/creditcart.png" alt="Creditcard" />
              <img src="/images/Logo-ZaloPay.png" alt="ZaloPay" />
              <img src="/images/Logo-MoMo.png" alt="Momo" />
              <img src="/images/Apple-Pay.png" alt="Apple Pay" />
              <img src="/images/Visa.png" alt="Visa" />
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
